version: '3.8'

# volumes:
#   redis-data:

services:

  redis:
    image: redis
    ports:
      - '6379:6379'
    command: redis-server
    # command: redis-server /etc/redis/redis.conf
    volumes:
      # - redis-data:/data
      # - ./redis:/etc/redis
      - ./redis/data:/data
    
  nextapp:
    build: .
    ports:
     - '4000:3000'
    depends_on:
      - redis
